# ABOUTME: Configuration for golangci-lint static analysis.
# ABOUTME: Defines enabled linters and their settings for code quality checks.

version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true

output:
  formats:
    text:
      path: stdout
